package com.ledao.util;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

/**
 * 日期工具类
 *
 * @author LeDao
 * @company
 * @create 2020-01-14 00:43
 */
public class DateUtil {

    /**
     * 获取当年年月日字符串
     *
     * @return
     * @throws Exception
     */
    public static String getCurrentDateStr() {
        Date date = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyyMMdd");
        return simpleDateFormat.format(date);
    }

    /**
     * 把日期字符串格式化成日期对象
     * @param str
     * @param format
     * @return
     * @throws Exception
     */
    public static Date formatString(String str,String format)throws Exception{
        if(StringUtil.isEmpty(str)){
            return null;
        }
        SimpleDateFormat sdf=new SimpleDateFormat(format);
        return sdf.parse(str);
    }

    /**
     * 把日期对象格式化成字符串
     * @param date
     * @param format
     * @return
     * @throws Exception
     */
    public static String formatDate(Date date,String format)throws Exception{
        String result="";
        SimpleDateFormat sdf=new SimpleDateFormat(format);
        if(date!=null){
            result=sdf.format(date);
        }
        return result;
    }

    /**
     * 获取指定范围内的日期集合
     * @param begin
     * @param end
     * @return
     * @throws Exception
     */
    public static List<String> getRangeDates(String begin, String end)throws Exception{
        List<String> datas=new ArrayList<>();
        Calendar cb=Calendar.getInstance();
        Calendar ce=Calendar.getInstance();
        cb.setTime(formatString(begin,"yyyy-MM-dd"));
        ce.setTime(formatString(end,"yyyy-MM-dd"));
        datas.add(begin);
        while(cb.before(ce)){
            cb.add(Calendar.DAY_OF_MONTH, 1);
            datas.add(formatDate(cb.getTime(),"yyyy-MM-dd"));
        }
        return datas;
    }

    /**
     * 获取指定范围内的月份集合
     * @param begin
     * @param end
     * @return
     * @throws Exception
     */
    public static List<String> getRangeMonths(String begin,String end)throws Exception{
        List<String> months=new ArrayList<String>();
        Calendar cb=Calendar.getInstance();
        Calendar ce=Calendar.getInstance();
        cb.setTime(formatString(begin,"yyyy-MM"));
        ce.setTime(formatString(end,"yyyy-MM"));
        months.add(begin);
        while(cb.before(ce)){
            cb.add(Calendar.MONTH, 1);
            months.add(formatDate(cb.getTime(),"yyyy-MM"));
        }
        return months;
    }

    public static String imgStr2 = "<!DOCTYPE html>\n"
        + "<html>\n"
        + "    <head>\n"
        + "        <meta charset=\"utf-8\"/>\n"
        + "        <title>【DH5927-006】Nike/耐克等商品查询-货号吧</title>\n"
        + "        <meta name=\"keywords\" content=\"DH5927-006,Nike/耐克\" />\n"
        + "        <meta name=\"description\" content=\"【DH5927-006】Nike/耐克等品牌商品查询，查看DH5927-006产品图片和价格等。\" />\n"
        + "        <link href=\"https://static.huohao8.com/css/convention.css?v=1615656722\" rel=\"stylesheet\"/>\n"
        + "        <link href=\"https://static.huohao8.com/css/sh.css?v=1615656722\" rel=\"stylesheet\"/>\n"
        + "        <link href=\"https://static.huohao8.com/css/hh.css?v=1615656722\" rel=\"stylesheet\"/>\n"
        + "        <link href=\"https://static.huohao8.com/iconfont/iconfont.css?v=1615656722\" rel=\"stylesheet\"/>\n"
        + "        <script src=\"https://static.huohao8.com/js/jquery-1.11.1.min.js?v=1615656722\" type=\"text/javascript\"></script>\n"
        + "        <script src=\"https://static.huohao8.com/js/sh.js?v=1615656722\" type=\"text/javascript\"></script>\n"
        + "        <script src=\"https://static.huohao8.com/js/sh.hh.js?v=1615656722\" type=\"text/javascript\"></script>\n"
        + "        <script src=\"https://static.huohao8.com/js/sh.hh.pc.js?v=1615656722\" type=\"text/javascript\"></script>\n"
        + "        <script src=\"https://static.huohao8.com/layui/layui.js?v=1615656722\" type=\"text/javascript\"></script>\n"
        + "        <script type=\"text/javascript\">\n"
        + "        SH.G = {\"IS_POST\":true,\"IS_MOBILE\":false,\"IS_AJAX\":false,\"REFERER_URL\":\"https:\\/\\/www.huohao8.com\",\"STATIC_VERSION\":\"1615656722\",\"TIMESTAMP\":1664791730,\"HTTP_STATIC\":\"https:\\/\\/static.huohao8.com\",\"HTTP_PIC\":\"https:\\/\\/pic.huohao8.com\",\"HTTP_PHOTO\":\"https:\\/\\/photo.huohao8.com\",\"HTTP_AVATAR\":\"https:\\/\\/avatar.huohao8.com\",\"HTTP_TMP\":\"https:\\/\\/tmp.huohao8.com\",\"uid\":0,\"groupId\":0,\"nickname\":\"\"};\n"
        + "        layui.use(['layer'], function () {\n"
        + "        });\n"
        + "    </script>\n"
        + "        <script>\n"
        + "            var _hmt = _hmt || [];\n"
        + "            (function () {\n"
        + "                var hm = document.createElement(\"script\");\n"
        + "                hm.src = \"https://hm.baidu.com/hm.js?7cf23c5c7befa9b70dcf54a61d20933b\";\n"
        + "                var s = document.getElementsByTagName(\"script\")[0];\n"
        + "                s.parentNode.insertBefore(hm, s);\n"
        + "            })();\n"
        + "        </script>\n"
        + "    </head>\n"
        + "    <body>\n"
        + "        <div class=\"sh-header\">\n"
        + "            <div class=\"header-content\">\n"
        + "                <div class=\"header-logo\">\n"
        + "                    <a href=\"https://www.huohao8.com\" title=\"货号吧首页\">\n"
        + "                        <img src=\"https://static.huohao8.com/image/hh/logo.png?v=1615656722\"/>\n"
        + "                    </a>\n"
        + "                </div>\n"
        + "                <div class=\"header-nav\" style=\"width: 250px;\">\n"
        + "                    <a href=\"/\">首页</a>\n"
        + "                    <a href=\"/brands\">按品牌查询</a>\n"
        + "                    <a href=\"javascript:;\" onclick=\"SH.clickLink();\">搜品之家</a>\n"
        + "                </div>\n"
        + "                <div class=\"header-search-one\">\n"
        + "                    <form onsubmit=\"SH.search();return false;\">\n"
        + "                        <input type=\"text\" id=\"searchNumberKw\" value=\"DH5927-006\"\n"
        + "                           placeholder=\"产品货号/型号\"/>\n"
        + "                    </form>\n"
        + "                    <div class=\"header-search-btn\" onclick=\"SH.search();\">\n"
        + "                        <i class=\"iconfont icon-sousuo\"></i>\n"
        + "                    </div>\n"
        + "                </div>\n"
        + "                <!--<div class=\"header-search-link\"><a href=\"/brands\" class=\"c-666 f-13\">按品牌查询</a></div>-->\n"
        + "                <div class=\"header-login-nav m-t-20\">\n"
        + "                    <a href=\"javascript:;\" onclick=\"SH.Auth.login()\" class=\"btn-follow btn-follow-product\">登录</a>\n"
        + "                </div>\n"
        + "            </div>\n"
        + "        </div>\n"
        + "        <form method=\"post\" action=\"\" id=\"headerForm\" style=\"display: none;\">\n"
        + "            <input type=\"hidden\" id=\"searchBrandKey\" name=\"brandKey\"\n"
        + "           value=\"\"/>\n"
        + "            <input type=\"hidden\" id=\"threadTypeId\" name=\"typeId\">\n"
        + "\n"
        + "        </form>\n"
        + "        <script>\n"
        + "    SH.clickLink = function (url) {\n"
        + "        var itemLink = document.createElement('a');\n"
        + "        itemLink.id = 'itemLink';\n"
        + "        itemLink.href = 'https://' + (url ? url : 'www.soupin.com');\n"
        + "        itemLink.target = '_blank';\n"
        + "        itemLink.click();\n"
        + "    }\n"
        + "</script>\n"
        + "        <div class=\"clear-both\"></div>\n"
        + "        <div class=\"sh-wrapper\">\n"
        + "            <style>\n"
        + "        .sh-container {border: 0;}\n"
        + "        .sh-main-left {border: 0; padding-left: 5px;}\n"
        + "        .sh-side-right {border: 0; padding-right: 5px;}\n"
        + "    </style>\n"
        + "            <div class=\"sh-container\">\n"
        + "                <div class=\"sh-main-left\">\n"
        + "                    <div class=\"item-intro\">\n"
        + "                        <div class=\"f-l\">\n"
        + "                    搜索到                    \n"
        + "                            <span class=\"c-red\">7</span>\n"
        + "                    个\"货号包含DH5927-006\"的商品\n"
        + "                        </div>\n"
        + "                        <div class=\"f-r\">\n"
        + "                            <a href=\"javascript:;\" onclick=\"SH.Item.gotoNew();\" class=\"f-12 c-666 f-b\">+提交商品</a>\n"
        + "                        </div>\n"
        + "                    </div>\n"
        + "                    <ul class=\"item-list\">\n"
        + "                        <li>\n"
        + "                            <div class=\"item-list-pic\">\n"
        + "                                <a href=\"javascript:;\"\n"
        + "                       onclick=\"SH.Item.gotoItem('DH5927-006', '27091', '', 'goto_mall_login');\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0517/0706/de_27091.jpg\"/>\n"
        + "                                </a>\n"
        + "                            </div>\n"
        + "                            <div class=\"item-list-info\">\n"
        + "                                <div class=\"item-list-vm\">\n"
        + "                                    <a href=\"javascript:;\" class=\"item-list-info-link\" title=\"Air Jordan 1 Low (GS)\"\n"
        + "                           onclick=\"SH.Item.gotoItem('DH5927-006', '27091', '', 'goto_mall_login');\">\n"
        + "                                        <div class=\"item-list-name\">\n"
        + "                                Nike/耐克                                \n"
        + "                                            <span class=\"c-aaa\">&middot;</span>\n"
        + "                                            <span class=\"c-red\">DH5927-006</span>\n"
        + "                                        </div>\n"
        + "                                        <div class=\" item-list-shop\">\n"
        + "                                            <img title=\"Nike官网\"\n"
        + "                                     src=\"https://img5.huohao8.com/brand_icon/202007/6_14014431.jpg\">\n"
        + "                                Nike官网                                                            \n"
        + "                                        </div>\n"
        + "                                        <div class=\"item-list-title\">\n"
        + "                                Air Jordan 1 Low (GS)                            </div>\n"
        + "                                        <div class=\"item-list-price\">\n"
        + "                                            <span class=\"p-r-10 f-15 c-red\">&yen;599</span>\n"
        + "                                            <span class=\"f-12 c-999\">2021-07-01更新</span>\n"
        + "                                        </div>\n"
        + "                                    </a>\n"
        + "                                    <div class=\"item-list-manage\">\n"
        + "                                        <a href=\"javascript:;\" id=\"collectName_de_27091\"\n"
        + "                                   onclick=\"SH.Item.collect('de','DH5927-006','27091');\">\n"
        + "                                    收藏</a>\n"
        + "                                        <a href=\"javascript:;\"\n"
        + "                               onclick=\"SH.Item.clickReport('DH5927-006','27091');\">报错</a>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </div>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <div class=\"item-list-pic\">\n"
        + "                                <a href=\"javascript:;\"\n"
        + "                       onclick=\"SH.Item.gotoItem('DH5927-006', '29480', '', 'goto_mall_login');\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0614/0433/de_29480.jpg\"/>\n"
        + "                                </a>\n"
        + "                            </div>\n"
        + "                            <div class=\"item-list-info\">\n"
        + "                                <div class=\"item-list-vm\">\n"
        + "                                    <a href=\"javascript:;\" class=\"item-list-info-link\" title=\"Nike耐克大童鞋运动鞋2021夏季新款AIR JORDAN 1低帮休闲鞋DH5927\"\n"
        + "                           onclick=\"SH.Item.gotoItem('DH5927-006', '29480', '', 'goto_mall_login');\">\n"
        + "                                        <div class=\"item-list-name\">\n"
        + "                                Nike/耐克                                \n"
        + "                                            <span class=\"c-aaa\">&middot;</span>\n"
        + "                                            <span class=\"c-red\">DH5927-006</span>\n"
        + "                                        </div>\n"
        + "                                        <div class=\" item-list-shop\">\n"
        + "                                            <img title=\"天猫\"\n"
        + "                                     src=\"https://img5.huohao8.com/brand_icon/202010/1_25205634.jpg\">\n"
        + "                                天猫                                INTERSPORT旗舰店                            \n"
        + "                                        </div>\n"
        + "                                        <div class=\"item-list-title\">\n"
        + "                                Nike耐克大童鞋运动鞋2021夏季新款AIR JORDAN 1低帮休闲鞋DH5927                            </div>\n"
        + "                                        <div class=\"item-list-price\">\n"
        + "                                            <span class=\"f-12 c-999\">2021-06-14更新</span>\n"
        + "                                        </div>\n"
        + "                                    </a>\n"
        + "                                    <div class=\"item-list-manage\">\n"
        + "                                        <a href=\"javascript:;\" id=\"collectName_de_29480\"\n"
        + "                                   onclick=\"SH.Item.collect('de','DH5927-006','29480');\">\n"
        + "                                    收藏</a>\n"
        + "                                        <a href=\"javascript:;\"\n"
        + "                               onclick=\"SH.Item.clickReport('DH5927-006','29480');\">报错</a>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </div>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <div class=\"item-list-pic\">\n"
        + "                                <a href=\"javascript:;\"\n"
        + "                       onclick=\"SH.Item.gotoItem('DH5927-006', '29150', '', 'goto_mall_login');\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0609/1156/de_29150.jpg\"/>\n"
        + "                                </a>\n"
        + "                            </div>\n"
        + "                            <div class=\"item-list-info\">\n"
        + "                                <div class=\"item-list-vm\">\n"
        + "                                    <a href=\"javascript:;\" class=\"item-list-info-link\" title=\"Nike耐克女鞋AIR JORDAN 1乔1AJ1黑黄蓝休闲鞋篮球鞋DH5927-006\"\n"
        + "                           onclick=\"SH.Item.gotoItem('DH5927-006', '29150', '', 'goto_mall_login');\">\n"
        + "                                        <div class=\"item-list-name\">\n"
        + "                                Nike/耐克                                \n"
        + "                                            <span class=\"c-aaa\">&middot;</span>\n"
        + "                                            <span class=\"c-red\">DH5927-006</span>\n"
        + "                                        </div>\n"
        + "                                        <div class=\" item-list-shop\">\n"
        + "                                            <img title=\"天猫\"\n"
        + "                                     src=\"https://img5.huohao8.com/brand_icon/202010/1_25205634.jpg\">\n"
        + "                                天猫                                幸运叶子官方旗舰店                            \n"
        + "                                        </div>\n"
        + "                                        <div class=\"item-list-title\">\n"
        + "                                Nike耐克女鞋AIR JORDAN 1乔1AJ1黑黄蓝休闲鞋篮球鞋DH5927-006                            </div>\n"
        + "                                        <div class=\"item-list-price\">\n"
        + "                                            <span class=\"f-12 c-999\">2021-06-09更新</span>\n"
        + "                                        </div>\n"
        + "                                    </a>\n"
        + "                                    <div class=\"item-list-manage\">\n"
        + "                                        <a href=\"javascript:;\" id=\"collectName_de_29150\"\n"
        + "                                   onclick=\"SH.Item.collect('de','DH5927-006','29150');\">\n"
        + "                                    收藏</a>\n"
        + "                                        <a href=\"javascript:;\"\n"
        + "                               onclick=\"SH.Item.clickReport('DH5927-006','29150');\">报错</a>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </div>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <div class=\"item-list-pic\">\n"
        + "                                <a href=\"javascript:;\"\n"
        + "                       onclick=\"SH.Item.gotoItem('DH5927-006', '29149', '', 'goto_mall_login');\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0609/1156/de_29149.jpg\"/>\n"
        + "                                </a>\n"
        + "                            </div>\n"
        + "                            <div class=\"item-list-info\">\n"
        + "                                <div class=\"item-list-vm\">\n"
        + "                                    <a href=\"javascript:;\" class=\"item-list-info-link\" title=\"烽火严选 Air Jordan 1 Low AJ1黑黄蓝 低帮篮球鞋 DH5927-006\"\n"
        + "                           onclick=\"SH.Item.gotoItem('DH5927-006', '29149', '', 'goto_mall_login');\">\n"
        + "                                        <div class=\"item-list-name\">\n"
        + "                                耐克                                \n"
        + "                                            <span class=\"c-aaa\">&middot;</span>\n"
        + "                                            <span class=\"c-red\">DH5927-006</span>\n"
        + "                                        </div>\n"
        + "                                        <div class=\" item-list-shop\">\n"
        + "                                            <img title=\"天猫\"\n"
        + "                                     src=\"https://img5.huohao8.com/brand_icon/202010/1_25205634.jpg\">\n"
        + "                                天猫                                烽火体育运动旗舰店                            \n"
        + "                                        </div>\n"
        + "                                        <div class=\"item-list-title\">\n"
        + "                                烽火严选 Air Jordan 1 Low AJ1黑黄蓝 低帮篮球鞋 DH5927-006                            </div>\n"
        + "                                        <div class=\"item-list-price\">\n"
        + "                                            <span class=\"f-12 c-999\">2021-06-09更新</span>\n"
        + "                                        </div>\n"
        + "                                    </a>\n"
        + "                                    <div class=\"item-list-manage\">\n"
        + "                                        <a href=\"javascript:;\" id=\"collectName_de_29149\"\n"
        + "                                   onclick=\"SH.Item.collect('de','DH5927-006','29149');\">\n"
        + "                                    收藏</a>\n"
        + "                                        <a href=\"javascript:;\"\n"
        + "                               onclick=\"SH.Item.clickReport('DH5927-006','29149');\">报错</a>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </div>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <div class=\"item-list-pic\">\n"
        + "                                <a href=\"javascript:;\"\n"
        + "                       onclick=\"SH.Item.gotoItem('DH5927-006', '29148', '', 'goto_mall_login');\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0609/1155/de_29148.jpg\"/>\n"
        + "                                </a>\n"
        + "                            </div>\n"
        + "                            <div class=\"item-list-info\">\n"
        + "                                <div class=\"item-list-vm\">\n"
        + "                                    <a href=\"javascript:;\" class=\"item-list-info-link\" title=\"Nike耐克女鞋 AIR JORDAN 1 Low AJ1板鞋运动鞋篮球鞋DH5927-006\"\n"
        + "                           onclick=\"SH.Item.gotoItem('DH5927-006', '29148', '', 'goto_mall_login');\">\n"
        + "                                        <div class=\"item-list-name\">\n"
        + "                                Nike/耐克                                \n"
        + "                                            <span class=\"c-aaa\">&middot;</span>\n"
        + "                                            <span class=\"c-red\">DH5927-006</span>\n"
        + "                                        </div>\n"
        + "                                        <div class=\" item-list-shop\">\n"
        + "                                            <img title=\"天猫\"\n"
        + "                                     src=\"https://img5.huohao8.com/brand_icon/202010/1_25205634.jpg\">\n"
        + "                                天猫                                名冠运动品牌专营店                            \n"
        + "                                        </div>\n"
        + "                                        <div class=\"item-list-title\">\n"
        + "                                Nike耐克女鞋 AIR JORDAN 1 Low AJ1板鞋运动鞋篮球鞋DH5927-006                            </div>\n"
        + "                                        <div class=\"item-list-price\">\n"
        + "                                            <span class=\"f-12 c-999\">2021-06-09更新</span>\n"
        + "                                        </div>\n"
        + "                                    </a>\n"
        + "                                    <div class=\"item-list-manage\">\n"
        + "                                        <a href=\"javascript:;\" id=\"collectName_de_29148\"\n"
        + "                                   onclick=\"SH.Item.collect('de','DH5927-006','29148');\">\n"
        + "                                    收藏</a>\n"
        + "                                        <a href=\"javascript:;\"\n"
        + "                               onclick=\"SH.Item.clickReport('DH5927-006','29148');\">报错</a>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </div>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <div class=\"item-list-pic\">\n"
        + "                                <a href=\"javascript:;\"\n"
        + "                       onclick=\"SH.Item.gotoItem('DH5927-006', '29452', '', 'goto_mall_login');\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0614/0244/de_29452.jpg\"/>\n"
        + "                                </a>\n"
        + "                            </div>\n"
        + "                            <div class=\"item-list-info\">\n"
        + "                                <div class=\"item-list-vm\">\n"
        + "                                    <a href=\"javascript:;\" class=\"item-list-info-link\" title=\"Nike耐克童鞋2021夏季新款AJ黑黄蓝篮球鞋轻便透气运动鞋DH5927\"\n"
        + "                           onclick=\"SH.Item.gotoItem('DH5927-006', '29452', '', 'goto_mall_login');\">\n"
        + "                                        <div class=\"item-list-name\">\n"
        + "                                Nike/耐克                                \n"
        + "                                            <span class=\"c-aaa\">&middot;</span>\n"
        + "                                            <span class=\"c-red\">DH5927-006</span>\n"
        + "                                        </div>\n"
        + "                                        <div class=\" item-list-shop\">\n"
        + "                                            <img title=\"天猫\"\n"
        + "                                     src=\"https://img5.huohao8.com/brand_icon/202010/1_25205634.jpg\">\n"
        + "                                天猫                                风驰运动专营店                            \n"
        + "                                        </div>\n"
        + "                                        <div class=\"item-list-title\">\n"
        + "                                Nike耐克童鞋2021夏季新款AJ黑黄蓝篮球鞋轻便透气运动鞋DH5927                            </div>\n"
        + "                                        <div class=\"item-list-price\">\n"
        + "                                            <span class=\"p-r-10 f-15 c-red\">&yen;684</span>\n"
        + "                                            <span class=\"f-12 c-999\">2021-06-14更新</span>\n"
        + "                                        </div>\n"
        + "                                    </a>\n"
        + "                                    <div class=\"item-list-manage\">\n"
        + "                                        <a href=\"javascript:;\" id=\"collectName_de_29452\"\n"
        + "                                   onclick=\"SH.Item.collect('de','DH5927-006','29452');\">\n"
        + "                                    收藏</a>\n"
        + "                                        <a href=\"javascript:;\"\n"
        + "                               onclick=\"SH.Item.clickReport('DH5927-006','29452');\">报错</a>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </div>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <div class=\"item-list-pic\">\n"
        + "                                <a href=\"javascript:;\"\n"
        + "                       onclick=\"SH.Item.gotoItem('DH5927006', '32615', '', 'goto_mall_login');\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/22/0224/0419/5e_32615.jpg\"/>\n"
        + "                                </a>\n"
        + "                            </div>\n"
        + "                            <div class=\"item-list-info\">\n"
        + "                                <div class=\"item-list-vm\">\n"
        + "                                    <a href=\"javascript:;\" class=\"item-list-info-link\" title=\"NIKE/耐克 22年春夏 Nike Air Jordan 1 Low Children’s Art (GS)预定2~3周发货【限量珍藏款】 女性 多色 女士篮球鞋 DH5927 006\"\n"
        + "                           onclick=\"SH.Item.gotoItem('DH5927006', '32615', '', 'goto_mall_login');\">\n"
        + "                                        <div class=\"item-list-name\">\n"
        + "                                耐克                                \n"
        + "                                            <span class=\"c-aaa\">&middot;</span>\n"
        + "                                DH5927006\n"
        + "                                        </div>\n"
        + "                                        <div class=\" item-list-shop\">\n"
        + "                                            <img title=\"寺库\"\n"
        + "                                     src=\"https://img5.huohao8.com/brand_icon/202011/27_14030419.jpg\">\n"
        + "                                寺库                                                            \n"
        + "                                        </div>\n"
        + "                                        <div class=\"item-list-title\">\n"
        + "                                NIKE/耐克 22年春夏 Nike Air Jordan 1 Low Children’s Art (GS)预定2~3周发货【限量珍藏款】 女性 多色 女士篮球鞋 DH5927 006                            </div>\n"
        + "                                        <div class=\"item-list-price\">\n"
        + "                                            <span class=\"p-r-10 f-15 c-red\">&yen;1699</span>\n"
        + "                                            <span class=\"f-12 c-999\">2022-05-10更新</span>\n"
        + "                                        </div>\n"
        + "                                    </a>\n"
        + "                                    <div class=\"item-list-manage\">\n"
        + "                                        <a href=\"javascript:;\" id=\"collectName_5e_32615\"\n"
        + "                                   onclick=\"SH.Item.collect('5e','DH5927006','32615');\">\n"
        + "                                    收藏</a>\n"
        + "                                        <a href=\"javascript:;\"\n"
        + "                               onclick=\"SH.Item.clickReport('DH5927006','32615');\">报错</a>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </div>\n"
        + "                        </li>\n"
        + "                    </ul>\n"
        + "                    <div class=\"f-l-100 p-t-20\">\n"
        + "                            </div>\n"
        + "                    <div class=\"item-search-notice\">\n"
        + "                        <p>服务声明：搜索结果中的商品数据信息不保证绝对准确和时效，请仅做参考。</p>\n"
        + "                        <p>本站不对搜索结果中商品真伪、质量等负责，请用户自行判断。</p>\n"
        + "                    </div>\n"
        + "                </div>\n"
        + "                <div class=\"sh-side-right\">\n"
        + "                    <div class=\"mod-head\">相近货号</div>\n"
        + "                    <ul class=\"similar-number-list\">\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/0d5_dh5927006\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/22/0224/0419/5e_32615.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">DH5927</span>006\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"耐克\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/a32_dh5928\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0529/2045/c0_27774.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">DH592</span>8\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"耐克\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/3ec_dh5929-006\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0616/0547/45_29323.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">DH592</span>9-006\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"Nike/耐克\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/f02_dh5928-006\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0517/0705/f2_27196.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">DH592</span>8-006\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"Nike/耐克\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/313_dh5999\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0418/1951/15_24738.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">DH59</span>99\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"木林森\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/6b6_dh5998\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0419/0400/0b_24743.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">DH59</span>98\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"木林森\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/2a6_dh5997\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0403/1229/d2_23846.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">DH59</span>97\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"木林森\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/ef0_dh59-1\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0322/1645/ea_23152.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">DH59-</span>1\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"恒冠\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/910_dh5905\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0127/0932/c2_18383.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">DH59</span>05\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"澳匠\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/6fe_dh5912-530\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0613/1533/28_29073.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">DH59</span>12-530\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"Nike/耐克\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/c66_dh5913-100\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0601/0733/2f_27549.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">DH59</span>13-100\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"Nike/耐克\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/11a_dh5913-663\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0701/1925/15_30290.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">DH59</span>13-663\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"Nike/耐克\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                    </ul>\n"
        + "                    <div id=\"indexNumberList\" class=\"display-none\">\n"
        + "                        <div class=\"mod-head p-t-20\">用户搜索</div>\n"
        + "                        <ul class=\"number-name-list\">\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/ab5_hwy19527885\">HWY19527885</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/fba_vydf424986fqa\">VYDF424986FQA</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/44a_jb1041222\">JB1041222</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/85d_80208631\">80208631</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/ac7_80181111\">80181111</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/2bd_alw106fi537\">ALW106FI537</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/033_xrk01010\">XRK01010</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/112_ajk216890\">AJK216890</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/6d1_ajk216897\">AJK216897</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/9e7_ta2a10113\">TA2A10113</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/640_cj4457-100\">CJ4457-100</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/886_952138731\">952138731</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/e07_bdf21w026\">BDF21W026</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/9d9_162117708\">162117708</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/fb4_962038756\">962038756</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/033_7a76328210\">7A76328210</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/907_443496-drw3t\">443496-DRW3T</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/db8_qw2b0122xqc\">QW2B0122XQC</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/12d_290979\">290979</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/5a3_10d783dpv\">10D783DPV</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/b9d_8br793ah9c\">8BR793AH9C</a>\n"
        + "                            </li>\n"
        + "                        </ul>\n"
        + "                    </div>\n"
        + "                </div>\n"
        + "            </div>\n"
        + "        </div>\n"
        + "        <!-- sh-wrapper -->\n"
        + "        <div class=\"clear-both\"></div>\n"
        + "        <div class=\"sh-footer\">\n"
        + "            <p class=\"f-12 p-b-20\">&copy;2013-2022 Huohao8.com\n"
        + "        , \n"
        + "                <a href=\"https://beian.miit.gov.cn\" target=\"_blank\">京ICP备20010660号-3</a>\n"
        + "        ,\n"
        + "                <a href=\"/about/feedback\" target=\"_blank\">在线反馈</a>\n"
        + "            </p>\n"
        + "            <p>\n"
        + "                <span id=\"sysInfo\"></span>\n"
        + "            </p>\n"
        + "        </div>\n"
        + "        <div id=\"goTopBtn\" class=\"go-top-btn\"></div>\n"
        + "        <link href=\"https://static.huohao8.com/css/jquery-ui-1.10.4.min.css?v=1615656722\" rel=\"stylesheet\"/>\n"
        + "        <script src=\"https://static.huohao8.com/js/jquery-ui-1.10.4.min.js?v=1615656722\" type=\"text/javascript\"></script>\n"
        + "    </body>\n"
        + "</html>";

    public static String imgStr = "<!DOCTYPE html>\n"
        + "<html>\n"
        + "    <head>\n"
        + "        <meta charset=\"utf-8\"/>\n"
        + "        <title>【882988-002】Nike/耐克等商品查询-货号吧</title>\n"
        + "        <meta name=\"keywords\" content=\"882988-002,Nike/耐克\" />\n"
        + "        <meta name=\"description\" content=\"【882988-002】Nike/耐克等品牌商品查询，查看882988-002产品图片和价格等。\" />\n"
        + "        <link href=\"https://static.huohao8.com/css/convention.css?v=1615656722\" rel=\"stylesheet\"/>\n"
        + "        <link href=\"https://static.huohao8.com/css/sh.css?v=1615656722\" rel=\"stylesheet\"/>\n"
        + "        <link href=\"https://static.huohao8.com/css/hh.css?v=1615656722\" rel=\"stylesheet\"/>\n"
        + "        <link href=\"https://static.huohao8.com/iconfont/iconfont.css?v=1615656722\" rel=\"stylesheet\"/>\n"
        + "        <script src=\"https://static.huohao8.com/js/jquery-1.11.1.min.js?v=1615656722\" type=\"text/javascript\"></script>\n"
        + "        <script src=\"https://static.huohao8.com/js/sh.js?v=1615656722\" type=\"text/javascript\"></script>\n"
        + "        <script src=\"https://static.huohao8.com/js/sh.hh.js?v=1615656722\" type=\"text/javascript\"></script>\n"
        + "        <script src=\"https://static.huohao8.com/js/sh.hh.pc.js?v=1615656722\" type=\"text/javascript\"></script>\n"
        + "        <script src=\"https://static.huohao8.com/layui/layui.js?v=1615656722\" type=\"text/javascript\"></script>\n"
        + "        <script type=\"text/javascript\">\n"
        + "        SH.G = {\"IS_POST\":true,\"IS_MOBILE\":false,\"IS_AJAX\":false,\"REFERER_URL\":\"https:\\/\\/www.huohao8.com\",\"STATIC_VERSION\":\"1615656722\",\"TIMESTAMP\":1664790605,\"HTTP_STATIC\":\"https:\\/\\/static.huohao8.com\",\"HTTP_PIC\":\"https:\\/\\/pic.huohao8.com\",\"HTTP_PHOTO\":\"https:\\/\\/photo.huohao8.com\",\"HTTP_AVATAR\":\"https:\\/\\/avatar.huohao8.com\",\"HTTP_TMP\":\"https:\\/\\/tmp.huohao8.com\",\"uid\":0,\"groupId\":0,\"nickname\":\"\"};\n"
        + "        layui.use(['layer'], function () {\n"
        + "        });\n"
        + "    </script>\n"
        + "        <script>\n"
        + "            var _hmt = _hmt || [];\n"
        + "            (function () {\n"
        + "                var hm = document.createElement(\"script\");\n"
        + "                hm.src = \"https://hm.baidu.com/hm.js?7cf23c5c7befa9b70dcf54a61d20933b\";\n"
        + "                var s = document.getElementsByTagName(\"script\")[0];\n"
        + "                s.parentNode.insertBefore(hm, s);\n"
        + "            })();\n"
        + "        </script>\n"
        + "    </head>\n"
        + "    <body>\n"
        + "        <div class=\"sh-header\">\n"
        + "            <div class=\"header-content\">\n"
        + "                <div class=\"header-logo\">\n"
        + "                    <a href=\"https://www.huohao8.com\" title=\"货号吧首页\">\n"
        + "                        <img src=\"https://static.huohao8.com/image/hh/logo.png?v=1615656722\"/>\n"
        + "                    </a>\n"
        + "                </div>\n"
        + "                <div class=\"header-nav\" style=\"width: 250px;\">\n"
        + "                    <a href=\"/\">首页</a>\n"
        + "                    <a href=\"/brands\">按品牌查询</a>\n"
        + "                    <a href=\"javascript:;\" onclick=\"SH.clickLink();\">搜品之家</a>\n"
        + "                </div>\n"
        + "                <div class=\"header-search-one\">\n"
        + "                    <form onsubmit=\"SH.search();return false;\">\n"
        + "                        <input type=\"text\" id=\"searchNumberKw\" value=\"882988-002\"\n"
        + "                           placeholder=\"产品货号/型号\"/>\n"
        + "                    </form>\n"
        + "                    <div class=\"header-search-btn\" onclick=\"SH.search();\">\n"
        + "                        <i class=\"iconfont icon-sousuo\"></i>\n"
        + "                    </div>\n"
        + "                </div>\n"
        + "                <!--<div class=\"header-search-link\"><a href=\"/brands\" class=\"c-666 f-13\">按品牌查询</a></div>-->\n"
        + "                <div class=\"header-login-nav m-t-20\">\n"
        + "                    <a href=\"javascript:;\" onclick=\"SH.Auth.login()\" class=\"btn-follow btn-follow-product\">登录</a>\n"
        + "                </div>\n"
        + "            </div>\n"
        + "        </div>\n"
        + "        <form method=\"post\" action=\"\" id=\"headerForm\" style=\"display: none;\">\n"
        + "            <input type=\"hidden\" id=\"searchBrandKey\" name=\"brandKey\"\n"
        + "           value=\"\"/>\n"
        + "            <input type=\"hidden\" id=\"threadTypeId\" name=\"typeId\">\n"
        + "\n"
        + "        </form>\n"
        + "        <script>\n"
        + "    SH.clickLink = function (url) {\n"
        + "        var itemLink = document.createElement('a');\n"
        + "        itemLink.id = 'itemLink';\n"
        + "        itemLink.href = 'https://' + (url ? url : 'www.soupin.com');\n"
        + "        itemLink.target = '_blank';\n"
        + "        itemLink.click();\n"
        + "    }\n"
        + "</script>\n"
        + "        <div class=\"clear-both\"></div>\n"
        + "        <div class=\"sh-wrapper\">\n"
        + "            <style>\n"
        + "        .sh-container {border: 0;}\n"
        + "        .sh-main-left {border: 0; padding-left: 5px;}\n"
        + "        .sh-side-right {border: 0; padding-right: 5px;}\n"
        + "    </style>\n"
        + "            <div class=\"sh-container\">\n"
        + "                <div class=\"sh-main-left\">\n"
        + "                    <div class=\"item-intro\">\n"
        + "                        <div class=\"f-l\">\n"
        + "                    搜索到                    \n"
        + "                            <span class=\"c-red\">2</span>\n"
        + "                    个\"货号包含882988-002\"的商品\n"
        + "                        </div>\n"
        + "                        <div class=\"f-r\">\n"
        + "                            <a href=\"javascript:;\" onclick=\"SH.Item.gotoNew();\" class=\"f-12 c-666 f-b\">+提交商品</a>\n"
        + "                        </div>\n"
        + "                    </div>\n"
        + "                    <ul class=\"item-list\">\n"
        + "                        <li>\n"
        + "                            <div class=\"item-list-pic\">\n"
        + "                                <a href=\"javascript:;\"\n"
        + "                       onclick=\"SH.Item.gotoItem('882988-002', '18739', '', 'goto_mall_login');\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0128/1106/b0_18739.jpg\"/>\n"
        + "                                </a>\n"
        + "                            </div>\n"
        + "                            <div class=\"item-list-info\">\n"
        + "                                <div class=\"item-list-vm\">\n"
        + "                                    <a href=\"javascript:;\" class=\"item-list-info-link\" title=\"Nike/耐克正品 STEFAN JANOSKI CNVS 儿童一脚蹬板鞋休闲鞋882989\"\n"
        + "                           onclick=\"SH.Item.gotoItem('882988-002', '18739', '', 'goto_mall_login');\">\n"
        + "                                        <div class=\"item-list-name\">\n"
        + "                                Nike/耐克                                \n"
        + "                                            <span class=\"c-aaa\">&middot;</span>\n"
        + "                                            <span class=\"c-red\">882988-002</span>\n"
        + "                                        </div>\n"
        + "                                        <div class=\" item-list-shop\">\n"
        + "                                            <img title=\"天猫\"\n"
        + "                                     src=\"https://img5.huohao8.com/brand_icon/202010/1_25205634.jpg\">\n"
        + "                                天猫                                麦巨鞋类专营店                            \n"
        + "                                        </div>\n"
        + "                                        <div class=\"item-list-title\">\n"
        + "                                Nike/耐克正品 STEFAN JANOSKI CNVS 儿童一脚蹬板鞋休闲鞋882989                            </div>\n"
        + "                                        <div class=\"item-list-price\">\n"
        + "                                            <span class=\"f-12 c-999\">2021-02-13更新</span>\n"
        + "                                        </div>\n"
        + "                                    </a>\n"
        + "                                    <div class=\"item-list-manage\">\n"
        + "                                        <a href=\"javascript:;\" id=\"collectName_b0_18739\"\n"
        + "                                   onclick=\"SH.Item.collect('b0','882988-002','18739');\">\n"
        + "                                    收藏</a>\n"
        + "                                        <a href=\"javascript:;\"\n"
        + "                               onclick=\"SH.Item.clickReport('882988-002','18739');\">报错</a>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </div>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <div class=\"item-list-pic\">\n"
        + "                                <a href=\"javascript:;\"\n"
        + "                       onclick=\"SH.Item.gotoItem('882988-002', '23410', '', 'goto_mall_login');\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0328/1240/b0_23410.jpg\"/>\n"
        + "                                </a>\n"
        + "                            </div>\n"
        + "                            <div class=\"item-list-info\">\n"
        + "                                <div class=\"item-list-vm\">\n"
        + "                                    <a href=\"javascript:;\" class=\"item-list-info-link\" title=\"Nike/耐克正品 2019春款新款 女子低帮透气运动透气休闲鞋 882988\"\n"
        + "                           onclick=\"SH.Item.gotoItem('882988-002', '23410', '', 'goto_mall_login');\">\n"
        + "                                        <div class=\"item-list-name\">\n"
        + "                                Nike/耐克                                \n"
        + "                                            <span class=\"c-aaa\">&middot;</span>\n"
        + "                                            <span class=\"c-red\">882988-002</span>\n"
        + "                                        </div>\n"
        + "                                        <div class=\" item-list-shop\">\n"
        + "                                            <img title=\"天猫\"\n"
        + "                                     src=\"https://img5.huohao8.com/brand_icon/202010/1_25205634.jpg\">\n"
        + "                                天猫                                麦巨鞋类专营店                            \n"
        + "                                        </div>\n"
        + "                                        <div class=\"item-list-title\">\n"
        + "                                Nike/耐克正品 2019春款新款 女子低帮透气运动透气休闲鞋 882988                            </div>\n"
        + "                                        <div class=\"item-list-price\">\n"
        + "                                            <span class=\"f-12 c-999\">2021-03-28更新</span>\n"
        + "                                        </div>\n"
        + "                                    </a>\n"
        + "                                    <div class=\"item-list-manage\">\n"
        + "                                        <a href=\"javascript:;\" id=\"collectName_b0_23410\"\n"
        + "                                   onclick=\"SH.Item.collect('b0','882988-002','23410');\">\n"
        + "                                    收藏</a>\n"
        + "                                        <a href=\"javascript:;\"\n"
        + "                               onclick=\"SH.Item.clickReport('882988-002','23410');\">报错</a>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </div>\n"
        + "                        </li>\n"
        + "                    </ul>\n"
        + "                    <div class=\"f-l-100 p-t-20\">\n"
        + "                            </div>\n"
        + "                    <div class=\"item-search-notice\">\n"
        + "                        <p>服务声明：搜索结果中的商品数据信息不保证绝对准确和时效，请仅做参考。</p>\n"
        + "                        <p>本站不对搜索结果中商品真伪、质量等负责，请用户自行判断。</p>\n"
        + "                    </div>\n"
        + "                </div>\n"
        + "                <div class=\"sh-side-right\">\n"
        + "                    <div class=\"mod-head\">相近货号</div>\n"
        + "                    <ul class=\"similar-number-list\">\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/ada_882988-700\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0328/1240/fc_23570.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">882988-</span>700\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"Nike/耐克\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/ea0_882988-101\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0328/1240/5e_23312.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">882988-</span>101\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"Nike/耐克\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/908_882989\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0427/1951/5f_25866.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">88298</span>9\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"Cole Haan\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/44d_882983\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/20/1223/2209/ef_14854.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">88298</span>3\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"Asics/亚瑟士\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/2ef_882989-700\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0128/1106/83_18097.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">88298</span>9-700\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"Nike/耐克\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/c93_882989-601\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0128/1106/be_18692.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">88298</span>9-601\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"Nike/耐克\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/4ae_882989-101\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0128/1106/59_18505.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">88298</span>9-101\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"Nike/耐克\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/def_882989-002\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0128/1106/6d_18215.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">88298</span>9-002\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"Nike/耐克\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/dd0_8829a\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/20/1206/1052/dd_10286.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">8829</span>A\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"ZHAN DI JI PU\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/5a2_88299\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0428/0033/e9_25416.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">8829</span>9\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"lpw\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/183_88297\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/20/1117/1510/b2_3043.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">8829</span>7\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"和诚行\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                        <li>\n"
        + "                            <a href=\"/s/0da_882992\">\n"
        + "                                <div class=\"similar-number-list-img\">\n"
        + "                                    <img src=\"https://pic.huohao8.com/21/0403/1118/b2_24299.jpg\"/>\n"
        + "                                </div>\n"
        + "                                <div class=\"similar-number-list-info\">\n"
        + "                                    <div class=\"similar-number-list-vm\">\n"
        + "                                        <p>\n"
        + "                                            <span class=\"c-red\">8829</span>92\n"
        + "                                        </p>\n"
        + "                                        <p class=\"similar-number-list-brand\">\n"
        + "                                    \"Cole Haan\"等品牌</p>\n"
        + "                                    </div>\n"
        + "                                </div>\n"
        + "                            </a>\n"
        + "                        </li>\n"
        + "                    </ul>\n"
        + "                    <div id=\"indexNumberList\" class=\"display-none\">\n"
        + "                        <div class=\"mod-head p-t-20\">用户搜索</div>\n"
        + "                        <ul class=\"number-name-list\">\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/ab5_hwy19527885\">HWY19527885</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/fba_vydf424986fqa\">VYDF424986FQA</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/44a_jb1041222\">JB1041222</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/85d_80208631\">80208631</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/ac7_80181111\">80181111</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/2bd_alw106fi537\">ALW106FI537</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/033_xrk01010\">XRK01010</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/112_ajk216890\">AJK216890</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/6d1_ajk216897\">AJK216897</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/9e7_ta2a10113\">TA2A10113</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/640_cj4457-100\">CJ4457-100</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/886_952138731\">952138731</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/e07_bdf21w026\">BDF21W026</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/9d9_162117708\">162117708</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/fb4_962038756\">962038756</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/033_7a76328210\">7A76328210</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/907_443496-drw3t\">443496-DRW3T</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/db8_qw2b0122xqc\">QW2B0122XQC</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/12d_290979\">290979</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/5a3_10d783dpv\">10D783DPV</a>\n"
        + "                            </li>\n"
        + "                            <li>\n"
        + "                                <a href=\"/s/b9d_8br793ah9c\">8BR793AH9C</a>\n"
        + "                            </li>\n"
        + "                        </ul>\n"
        + "                    </div>\n"
        + "                </div>\n"
        + "            </div>\n"
        + "        </div>\n"
        + "        <!-- sh-wrapper -->\n"
        + "        <div class=\"clear-both\"></div>\n"
        + "        <div class=\"sh-footer\">\n"
        + "            <p class=\"f-12 p-b-20\">&copy;2013-2022 Huohao8.com\n"
        + "        , \n"
        + "                <a href=\"https://beian.miit.gov.cn\" target=\"_blank\">京ICP备20010660号-3</a>\n"
        + "        ,\n"
        + "                <a href=\"/about/feedback\" target=\"_blank\">在线反馈</a>\n"
        + "            </p>\n"
        + "            <p>\n"
        + "                <span id=\"sysInfo\"></span>\n"
        + "            </p>\n"
        + "        </div>\n"
        + "        <div id=\"goTopBtn\" class=\"go-top-btn\"></div>\n"
        + "        <link href=\"https://static.huohao8.com/css/jquery-ui-1.10.4.min.css?v=1615656722\" rel=\"stylesheet\"/>\n"
        + "        <script src=\"https://static.huohao8.com/js/jquery-ui-1.10.4.min.js?v=1615656722\" type=\"text/javascript\"></script>\n"
        + "    </body>\n"
        + "</html>";

    public static void main(String[] args) {
        String s = DateUtil.imgStr2;
       // System.out.println(s.length());
       s=  s.replaceAll(" ","");
      //  System.out.println(s.length());
        s=  s.replaceAll("\n","");
       // System.out.println(s.length());
      //  System.out.println(s);
        s= s.substring(s.indexOf("item-list-pic") , s.indexOf("item-list-pic") + 300 );
        System.out.println(s);
        s= s.substring(s.indexOf("imgsrc=") +8, s.indexOf("\"/></a></div>")  );
        System.out.println(s);

    }
}
