server:
  port: 8013
file-save-path: G://dw//img//
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: csy@123
    url: jdbc:mysql://localhost:3306/db_jxc?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
